/**
 * @file Automatically generated by barrelsby.
 */

export * from './notice-board.repository';
export * from './notifications-infrastructure.module';
export * from './schemas/notice-board.schema';
