/**
 * @file Automatically generated by barrelsby.
 */

export * from './master-facility.repository';
export * from './registries-infrastructure.module';
export * from './schemas/master-facility.schema';
